<?php echo $this->renderTabs($this->tabs); ?>
<?php echo $this->renderSmallTools($this->smallTools); ?>
<?php echo "<p><h4>$this->text</h4></p>"; ?>
<p>
	You can use auto responders to send a message back automatically to anyone who sends an email to a specified account. This can be useful for times when you are on vacation or unavailable, or if you have a generic message that you wish to send from a support email address.
</p>
<?php echo $this->renderList($this->list); ?>
<?php echo $this->button; ?>