<?php echo $this->renderTabs($this->tabs); ?>

<?php echo $this->renderSmallTools($this->smallTools); ?>

<?php echo "<p><h4>$this->text</h4></p>"; ?>

<?php echo 
	"Hint: If you do not create a forwarder or email account with the same address as this auto responder, mail will only be handled by the auto responder before it is discarded.

	When configuring an auto responder, you can use the following tags to insert information into the response email:

	^S	-	The subject of the message sent to the auto responder.
	^F	-	The name of the sender of the message received by the auto responder, if available.
	^R	-	The incoming email sender's address."; ?>



<?php echo $this->form; ?>