<?php echo $this->renderTabs($this->tabs); ?>
<?php echo $this->renderSmallTools($this->smallTools); ?>
<?php echo "<p><h4>$this->text</h4></p>"; ?>
<p class='description'>
Groups allow a group of people to exchange emails by using a single email address (for example support@mycompany.com), . Groups can be private (only members of the group can submit emails to the group) or public (anybody can send an email to the group).
</p>
<?php echo $this->renderList($this->list); ?>
<?php echo $this->button; ?>
