<?php echo $this->renderTabs($this->tabs); ?>
<?php echo $this->renderSmallTools($this->smallTools); ?>
<?php echo "<p><h4>$this->heading</h4></p>"; ?>
<p class="description">The default email address will "catch" any mail that is sent to an invalid email address for your domain. You can also choose to Discard, Reject, or Accept and bounce any mails sent to an invalid email address for your domain.</p>
<?php echo $this->form; ?>
